/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BertResult {
  'emotion' : string,
  'brandSpecific' : [] | [string],
  'confidence' : number,
}
export interface BrandIntentionCorrelation {
  'low' : bigint,
  'high' : bigint,
  'brand' : string,
  'medium' : bigint,
}
export interface CleaningLog {
  'status' : string,
  'step' : string,
  'timestamp' : bigint,
}
export interface ConfusionMatrixResult {
  'model' : string,
  'confusionMatrix' : Array<Array<number>>,
  'emotions' : Array<string>,
  'confusionMatrixRaw' : Array<Array<bigint>>,
}
export interface Document {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface GenderDistribution {
  'emotionDistribution' : Array<GenderDistributionEntry>,
  'brandDistribution' : Array<GenderDistributionEntry>,
}
export interface GenderDistributionEntry {
  'maleCount' : number,
  'femaleCount' : number,
  'category' : string,
}
export interface GeoLocationDistribution {
  'data' : Array<Array<number>>,
  'emotions' : Array<string>,
  'locations' : Array<string>,
}
export interface IntentionResult {
  'brandCorrelation' : Array<BrandIntentionCorrelation>,
  'trends' : Array<IntentionTrend>,
  'individual' : PurchaseIntention,
  'distribution' : PurchaseIntentionDistribution,
}
export interface IntentionTrend {
  'id' : bigint,
  'trend' : bigint,
  'intentionLevel' : string,
}
export type Principal = Principal;
export interface PurchaseIntention {
  'level' : string,
  'score' : bigint,
  'gender' : [] | [string],
  'brand' : [] | [string],
  'location' : [] | [string],
}
export interface PurchaseIntentionDistribution {
  'low' : bigint,
  'high' : bigint,
  'medium' : bigint,
}
export interface _SERVICE {
  'addCleaningLog' : ActorMethod<[Array<CleaningLog>], bigint>,
  'analyzeGenderDistribution' : ActorMethod<[], GenderDistribution>,
  'analyzeGeoDistribution' : ActorMethod<
    [Array<Array<string>>],
    GeoLocationDistribution
  >,
  'analyzeText' : ActorMethod<[string], BertResult>,
  'calculateIntention' : ActorMethod<
    [string, string, string, string],
    IntentionResult
  >,
  'deleteDocument' : ActorMethod<[bigint], boolean>,
  'getAllDocuments' : ActorMethod<[], Array<Document>>,
  'getCleaningLog' : ActorMethod<[bigint], [] | [Array<CleaningLog>]>,
  'getConfusionMatrix' : ActorMethod<[string], ConfusionMatrixResult>,
  'getDocument' : ActorMethod<[bigint], [] | [Document]>,
  'getLatestCleaningLog' : ActorMethod<[], [] | [Array<CleaningLog>]>,
  'processCorrect' : ActorMethod<[string], undefined>,
  'processIncorrect' : ActorMethod<[string, string, string, string], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'resetModelData' : ActorMethod<[string], undefined>,
  'uploadDocument' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];