/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CleaningLog = IDL.Record({
  'status' : IDL.Text,
  'step' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const GenderDistributionEntry = IDL.Record({
  'maleCount' : IDL.Float64,
  'femaleCount' : IDL.Float64,
  'category' : IDL.Text,
});
export const GenderDistribution = IDL.Record({
  'emotionDistribution' : IDL.Vec(GenderDistributionEntry),
  'brandDistribution' : IDL.Vec(GenderDistributionEntry),
});
export const GeoLocationDistribution = IDL.Record({
  'data' : IDL.Vec(IDL.Vec(IDL.Float64)),
  'emotions' : IDL.Vec(IDL.Text),
  'locations' : IDL.Vec(IDL.Text),
});
export const BertResult = IDL.Record({
  'emotion' : IDL.Text,
  'brandSpecific' : IDL.Opt(IDL.Text),
  'confidence' : IDL.Float64,
});
export const BrandIntentionCorrelation = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'brand' : IDL.Text,
  'medium' : IDL.Nat,
});
export const IntentionTrend = IDL.Record({
  'id' : IDL.Nat,
  'trend' : IDL.Int,
  'intentionLevel' : IDL.Text,
});
export const PurchaseIntention = IDL.Record({
  'level' : IDL.Text,
  'score' : IDL.Int,
  'gender' : IDL.Opt(IDL.Text),
  'brand' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const PurchaseIntentionDistribution = IDL.Record({
  'low' : IDL.Nat,
  'high' : IDL.Nat,
  'medium' : IDL.Nat,
});
export const IntentionResult = IDL.Record({
  'brandCorrelation' : IDL.Vec(BrandIntentionCorrelation),
  'trends' : IDL.Vec(IntentionTrend),
  'individual' : PurchaseIntention,
  'distribution' : PurchaseIntentionDistribution,
});
export const Principal = IDL.Principal;
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : Principal,
  'timestamp' : IDL.Int,
});
export const ConfusionMatrixResult = IDL.Record({
  'model' : IDL.Text,
  'confusionMatrix' : IDL.Vec(IDL.Vec(IDL.Float64)),
  'emotions' : IDL.Vec(IDL.Text),
  'confusionMatrixRaw' : IDL.Vec(IDL.Vec(IDL.Nat)),
});

export const idlService = IDL.Service({
  'addCleaningLog' : IDL.Func([IDL.Vec(CleaningLog)], [IDL.Nat], []),
  'analyzeGenderDistribution' : IDL.Func([], [GenderDistribution], ['query']),
  'analyzeGeoDistribution' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Text))],
      [GeoLocationDistribution],
      [],
    ),
  'analyzeText' : IDL.Func([IDL.Text], [BertResult], ['query']),
  'calculateIntention' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IntentionResult],
      [],
    ),
  'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getCleaningLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(CleaningLog))],
      ['query'],
    ),
  'getConfusionMatrix' : IDL.Func(
      [IDL.Text],
      [ConfusionMatrixResult],
      ['query'],
    ),
  'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
  'getLatestCleaningLog' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(CleaningLog))],
      ['query'],
    ),
  'processCorrect' : IDL.Func([IDL.Text], [], []),
  'processIncorrect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'resetAllData' : IDL.Func([], [], []),
  'resetModelData' : IDL.Func([IDL.Text], [], []),
  'uploadDocument' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CleaningLog = IDL.Record({
    'status' : IDL.Text,
    'step' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const GenderDistributionEntry = IDL.Record({
    'maleCount' : IDL.Float64,
    'femaleCount' : IDL.Float64,
    'category' : IDL.Text,
  });
  const GenderDistribution = IDL.Record({
    'emotionDistribution' : IDL.Vec(GenderDistributionEntry),
    'brandDistribution' : IDL.Vec(GenderDistributionEntry),
  });
  const GeoLocationDistribution = IDL.Record({
    'data' : IDL.Vec(IDL.Vec(IDL.Float64)),
    'emotions' : IDL.Vec(IDL.Text),
    'locations' : IDL.Vec(IDL.Text),
  });
  const BertResult = IDL.Record({
    'emotion' : IDL.Text,
    'brandSpecific' : IDL.Opt(IDL.Text),
    'confidence' : IDL.Float64,
  });
  const BrandIntentionCorrelation = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'brand' : IDL.Text,
    'medium' : IDL.Nat,
  });
  const IntentionTrend = IDL.Record({
    'id' : IDL.Nat,
    'trend' : IDL.Int,
    'intentionLevel' : IDL.Text,
  });
  const PurchaseIntention = IDL.Record({
    'level' : IDL.Text,
    'score' : IDL.Int,
    'gender' : IDL.Opt(IDL.Text),
    'brand' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const PurchaseIntentionDistribution = IDL.Record({
    'low' : IDL.Nat,
    'high' : IDL.Nat,
    'medium' : IDL.Nat,
  });
  const IntentionResult = IDL.Record({
    'brandCorrelation' : IDL.Vec(BrandIntentionCorrelation),
    'trends' : IDL.Vec(IntentionTrend),
    'individual' : PurchaseIntention,
    'distribution' : PurchaseIntentionDistribution,
  });
  const Principal = IDL.Principal;
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : Principal,
    'timestamp' : IDL.Int,
  });
  const ConfusionMatrixResult = IDL.Record({
    'model' : IDL.Text,
    'confusionMatrix' : IDL.Vec(IDL.Vec(IDL.Float64)),
    'emotions' : IDL.Vec(IDL.Text),
    'confusionMatrixRaw' : IDL.Vec(IDL.Vec(IDL.Nat)),
  });
  
  return IDL.Service({
    'addCleaningLog' : IDL.Func([IDL.Vec(CleaningLog)], [IDL.Nat], []),
    'analyzeGenderDistribution' : IDL.Func([], [GenderDistribution], ['query']),
    'analyzeGeoDistribution' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Text))],
        [GeoLocationDistribution],
        [],
      ),
    'analyzeText' : IDL.Func([IDL.Text], [BertResult], ['query']),
    'calculateIntention' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IntentionResult],
        [],
      ),
    'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getCleaningLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(CleaningLog))],
        ['query'],
      ),
    'getConfusionMatrix' : IDL.Func(
        [IDL.Text],
        [ConfusionMatrixResult],
        ['query'],
      ),
    'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
    'getLatestCleaningLog' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(CleaningLog))],
        ['query'],
      ),
    'processCorrect' : IDL.Func([IDL.Text], [], []),
    'processIncorrect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'resetAllData' : IDL.Func([], [], []),
    'resetModelData' : IDL.Func([IDL.Text], [], []),
    'uploadDocument' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };