/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IntentionTrend {
    id: bigint;
    trend: bigint;
    intentionLevel: string;
}
export interface ConfusionMatrixResult {
    model: string;
    confusionMatrix: Array<Array<number>>;
    emotions: Array<string>;
    confusionMatrixRaw: Array<Array<bigint>>;
}
export interface PurchaseIntention {
    level: string;
    score: bigint;
    gender?: string;
    brand?: string;
    location?: string;
}
export interface IntentionResult {
    brandCorrelation: Array<BrandIntentionCorrelation>;
    trends: Array<IntentionTrend>;
    individual: PurchaseIntention;
    distribution: PurchaseIntentionDistribution;
}
export interface GeoLocationDistribution {
    data: Array<Array<number>>;
    emotions: Array<string>;
    locations: Array<string>;
}
export interface GenderDistribution {
    emotionDistribution: Array<GenderDistributionEntry>;
    brandDistribution: Array<GenderDistributionEntry>;
}
export interface BrandIntentionCorrelation {
    low: bigint;
    high: bigint;
    brand: string;
    medium: bigint;
}
export interface Document {
    id: bigint;
    content: string;
    author: Principal;
    timestamp: bigint;
}
export type Principal = Principal;
export interface PurchaseIntentionDistribution {
    low: bigint;
    high: bigint;
    medium: bigint;
}
export interface GenderDistributionEntry {
    maleCount: number;
    femaleCount: number;
    category: string;
}
export interface CleaningLog {
    status: string;
    step: string;
    timestamp: bigint;
}
export interface BertResult {
    emotion: string;
    brandSpecific?: string;
    confidence: number;
}
export interface backendInterface {
    addCleaningLog(_logs: Array<CleaningLog>): Promise<bigint>;
    analyzeGenderDistribution(): Promise<GenderDistribution>;
    analyzeGeoDistribution(_texts: Array<Array<string>>): Promise<GeoLocationDistribution>;
    analyzeText(input: string): Promise<BertResult>;
    calculateIntention(input: string, gender: string, location: string, brand: string): Promise<IntentionResult>;
    deleteDocument(id: bigint): Promise<boolean>;
    getAllDocuments(): Promise<Array<Document>>;
    getCleaningLog(id: bigint): Promise<Array<CleaningLog> | null>;
    getConfusionMatrix(modelName: string): Promise<ConfusionMatrixResult>;
    getDocument(id: bigint): Promise<Document | null>;
    getLatestCleaningLog(): Promise<Array<CleaningLog> | null>;
    processCorrect(text: string): Promise<void>;
    processIncorrect(_content: string, model: string, actualEmotion: string, predictedEmotion: string): Promise<void>;
    resetAllData(): Promise<void>;
    resetModelData(modelName: string): Promise<void>;
    uploadDocument(content: string): Promise<bigint>;
}
import type { BertResult as _BertResult, BrandIntentionCorrelation as _BrandIntentionCorrelation, CleaningLog as _CleaningLog, Document as _Document, IntentionResult as _IntentionResult, IntentionTrend as _IntentionTrend, PurchaseIntention as _PurchaseIntention, PurchaseIntentionDistribution as _PurchaseIntentionDistribution } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCleaningLog(arg0: Array<CleaningLog>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCleaningLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCleaningLog(arg0);
            return result;
        }
    }
    async analyzeGenderDistribution(): Promise<GenderDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeGenderDistribution();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeGenderDistribution();
            return result;
        }
    }
    async analyzeGeoDistribution(arg0: Array<Array<string>>): Promise<GeoLocationDistribution> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeGeoDistribution(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeGeoDistribution(arg0);
            return result;
        }
    }
    async analyzeText(arg0: string): Promise<BertResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeText(arg0);
                return from_candid_BertResult_n1(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeText(arg0);
            return from_candid_BertResult_n1(this.uploadFile, this.downloadFile, result);
        }
    }
    async calculateIntention(arg0: string, arg1: string, arg2: string, arg3: string): Promise<IntentionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateIntention(arg0, arg1, arg2, arg3);
                return from_candid_IntentionResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateIntention(arg0, arg1, arg2, arg3);
            return from_candid_IntentionResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async deleteDocument(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async getAllDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return result;
        }
    }
    async getCleaningLog(arg0: bigint): Promise<Array<CleaningLog> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCleaningLog(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCleaningLog(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getConfusionMatrix(arg0: string): Promise<ConfusionMatrixResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfusionMatrix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfusionMatrix(arg0);
            return result;
        }
    }
    async getDocument(arg0: bigint): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getLatestCleaningLog(): Promise<Array<CleaningLog> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestCleaningLog();
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestCleaningLog();
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async processCorrect(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processCorrect(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCorrect(arg0);
            return result;
        }
    }
    async processIncorrect(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processIncorrect(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processIncorrect(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async resetAllData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllData();
            return result;
        }
    }
    async resetModelData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetModelData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetModelData(arg0);
            return result;
        }
    }
    async uploadDocument(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0);
            return result;
        }
    }
}
function from_candid_BertResult_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BertResult): BertResult {
    return from_candid_record_n2(uploadFile, downloadFile, value);
}
function from_candid_IntentionResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntentionResult): IntentionResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_PurchaseIntention_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseIntention): PurchaseIntention {
    return from_candid_record_n7(uploadFile, downloadFile, value);
}
function from_candid_opt_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_CleaningLog>]): Array<CleaningLog> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emotion: string;
    brandSpecific: [] | [string];
    confidence: number;
}): {
    emotion: string;
    brandSpecific?: string;
    confidence: number;
} {
    return {
        emotion: value.emotion,
        brandSpecific: record_opt_to_undefined(from_candid_opt_n3(uploadFile, downloadFile, value.brandSpecific)),
        confidence: value.confidence
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    brandCorrelation: Array<_BrandIntentionCorrelation>;
    trends: Array<_IntentionTrend>;
    individual: _PurchaseIntention;
    distribution: _PurchaseIntentionDistribution;
}): {
    brandCorrelation: Array<BrandIntentionCorrelation>;
    trends: Array<IntentionTrend>;
    individual: PurchaseIntention;
    distribution: PurchaseIntentionDistribution;
} {
    return {
        brandCorrelation: value.brandCorrelation,
        trends: value.trends,
        individual: from_candid_PurchaseIntention_n6(uploadFile, downloadFile, value.individual),
        distribution: value.distribution
    };
}
function from_candid_record_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    level: string;
    score: bigint;
    gender: [] | [string];
    brand: [] | [string];
    location: [] | [string];
}): {
    level: string;
    score: bigint;
    gender?: string;
    brand?: string;
    location?: string;
} {
    return {
        level: value.level,
        score: value.score,
        gender: record_opt_to_undefined(from_candid_opt_n3(uploadFile, downloadFile, value.gender)),
        brand: record_opt_to_undefined(from_candid_opt_n3(uploadFile, downloadFile, value.brand)),
        location: record_opt_to_undefined(from_candid_opt_n3(uploadFile, downloadFile, value.location))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
